Repository upb-uc4/hlf-api, pull requests merged in 2020-08, with the labels that each got.

#2 Feature/new error codes
  CHANGELOG.md
  project/Commons.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/exceptions/HyperledgerInnerException.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/exceptions/InvalidCallException.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/exceptions/TransactionErrorException.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/exceptions/TransactionException.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/traits/ChaincodeActionsTraitCourses.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/traits/ChaincodeActionsTraitInternal.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/traits/ChaincodeActionsTraitStudents.scala
Labels: enhancement

#5 Feature/optimize pipelines
  .github/actions/dev_network_test/action.yml
  .github/workflows/dev_network_test.yml
  src/test/scala/CourseAccessTests.scala
Labels: enhancement

#8 Bugfix/error propagation
  .github/workflows/dev_network_test.yml
  src/main/scala/de/upb/cs/uc4/hyperledger/traits/ChaincodeActionsTrait.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/traits/ChaincodeActionsTraitCourses.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/traits/ChaincodeActionsTraitInternal.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/traits/ChaincodeActionsTraitStudents.scala
  src/test/scala/CourseAccessTests.scala
  src/test/scala/MatriculationErrorTests.scala
Labels: bug

#13 issue12 :: rename AbstractConnectionTrait
  CHANGELOG.md
  src/main/scala/de/upb/cs/uc4/hyperledger/connections/traits/ConnectionCourseTrait.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/connections/traits/ConnectionMatriculationTrait.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/connections/traits/ConnectionTrait.scala
Labels: bug, hyperledger

#20 Feature/formatter reports
  .github/actions/dev_network_test/action.yml
  .github/actions/prod_network_test/action.yml
  .github/workflows/dev_network_test.yml
  .github/workflows/production_network_test.yml
  .github/workflows/style_check.yaml
  .scalariform.conf
  build.sbt
  project/Commons.scala
  project/Dependencies.scala
  project/plugins.sbt
  src/main/scala/RegisterUser.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/connections/cases/ConnectionCourses.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/connections/cases/ConnectionMatriculation.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/connections/traits/ConnectionCourseTrait.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/connections/traits/ConnectionMatriculationTrait.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/connections/traits/ConnectionTrait.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/exceptions/TransactionException.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/exceptions/traits/HyperledgerExceptionTrait.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/exceptions/traits/TransactionExceptionTrait.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/utilities/ConnectionManager.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/utilities/EnrollmentManager.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/utilities/GatewayManager.scala
  src/main/scala/de/upb/cs/uc4/hyperledger/utilities/WalletManager.scala
  src/test/scala/CourseErrorTests.scala
  src/test/scala/EnrollmentTests.scala
  src/test/scala/ManagerTests.scala
  src/test/scala/MatriculationErrorTests.scala
  src/test/scala/de/upb/cs/uc4/hyperledger/testBase/TestBaseDevNetwork.scala
  src/test/scala/de/upb/cs/uc4/hyperledger/testBase/TestBaseGeneral.scala
  src/test/scala/de/upb/cs/uc4/hyperledger/testBase/TestBaseProductionNetwork.scala
Labels: enhancement, hyperledger

#26 Feature/test matriculation api
  .github/workflows/dev_network_test.yml
  .github/workflows/production_network_test.yml
  .gitignore
  src/test/scala/de/upb/cs/uc4/hyperledger/testBase/TestBase.scala
  src/test/scala/de/upb/cs/uc4/hyperledger/testData/TestDataMatriculation.scala
  src/test/scala/de/upb/cs/uc4/hyperledger/tests/MatriculationAccessTests.scala
  src/test/scala/de/upb/cs/uc4/hyperledger/tests/MatriculationErrorTests.scala
Labels: enhancement
